_wandb:
    value:
        cli_version: 0.22.2
        e:
            bvitgsjvch978b1hxesflwervcmq6hvd:
                args:
                    - --output-dir
                    - .\artifacts
                    - --test-size
                    - "0.2"
                    - --seed
                    - "42"
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "166077657088"
                        used: "57273454592"
                email: raja.ramiz.mukhtar6@gmail.com
                executable: D:\MLOPSPROJECT2\mlops-capstone\.venv\Scripts\python.exe
                host: DESKTOP-90G5JM7
                memory:
                    total: "16810217472"
                os: Windows-10-10.0.19045-SP0
                program: D:\MLOPSPROJECT2\mlops-capstone\src\train.py
                python: CPython 3.13.7
                root: D:\MLOPSPROJECT2\mlops-capstone
                startedAt: "2025-10-22T13:27:32.553596Z"
                writerId: bvitgsjvch978b1hxesflwervcmq6hvd
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.13.7
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
output_dir:
    value: .\artifacts
seed:
    value: 42
test_size:
    value: 0.2
