name: Train and register model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Normalize W&B secret names
        run: |
          echo "Checking for alternative W&B secret names..."
          # If WANDB_API_KEY not set but a secret named WANDBAPIKEY exists, map it
          if [ -z "${WANDB_API_KEY}" ] && [ "${{ secrets.WANDBAPIKEY }}" != "" ]; then
            echo "WANDB_API_KEY=${{ secrets.WANDBAPIKEY }}" >> $GITHUB_ENV
            echo "Mapped secrets.WANDBAPIKEY -> WANDB_API_KEY"
          fi

      - name: Check W&B secrets
        run: |
          if [ -z "${WANDB_API_KEY}" ]; then
            echo "ERROR: WANDB_API_KEY secret is not set in this repository. Please add it to GitHub Secrets." >&2
            exit 1
          fi
          echo "WANDB secrets appear to be set"

      - name: Run training
        run: |
          python src/train.py --output-dir ./artifacts
