name: Train and register model

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/train-and-register.yml'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Configure W&B
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
        run: |
          if [ -z "$WANDB_API_KEY" ]; then
            echo "ERROR: WANDB_API_KEY secret is not set" >&2
            exit 1
          fi
          echo "WANDB_API_KEY is configured"
          echo "WANDB_ENTITY=$WANDB_ENTITY" >> $GITHUB_ENV
          echo "WANDB_PROJECT=$WANDB_PROJECT" >> $GITHUB_ENV
          echo "WANDB_API_KEY=$WANDB_API_KEY" >> $GITHUB_ENV

      - name: Run training
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
        run: |
          python src/train.py --output-dir ./artifacts
